name: remote_bf
version: 1.0.0+1
publish_to: none
description: flutter for bodyfirend application
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  cached_network_image: 3.2.3
  fluttertoast: 8.2.2
  flutter_svg: 2.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/logo/
    - assets/icon/

  uses-material-design: true

